[build-system]
requires = ["setuptools>=80.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "github-agent"
version = "0.2.4"
readme = "README.md"
description = "GitHub Agent for MCP"
requires-python = ">=3.10"
authors = [{ name = "Audel Rouhi", email = "knucklessg1@gmail.com" }]
license = { text = "MIT" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: Public Domain",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
]
dependencies = [
    "pydantic-ai-slim[fastmcp,openai,anthropic,groq,mistral,google,huggingface,a2a,ag-ui,web]>=1.58.0",
    "pydantic-ai-skills>=v0.4.0",
    "fastapi>=0.128.0",
    "fastmcp",
    "uvicorn",
    "fastapi",
]

[project.scripts]
github-agent = "github_agent.github_agent:agent_server"


[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
ansible_tower_mcp = ["mcp_config.json", "skills/**"]
